sudo: required
dist: trusty

language: node_js
node_js:
  - '5.7.1'

before_script:
  - gem install compass
  - npm install -g grunt-cli
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install

script:
  - grunt build:production

deploy:
  on:
    branch: production
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "test-deployment-pba"
  skip_cleanup: true
  local_dir: dist
