sudo: required
dist: trusty

language: node_js
node_js:
  - '5.7.1'

before_script:
  - gem install compass
  - npm install -g grunt-cli
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install

script:
  - grunt build:production

deploy:
  provider: script
  script: "curl --ftp-create-dirs -T dist/pba-client-dist.zip -u $FTP_USER:$FTP_PASSWORD ftp://cirightone.com/pba/pba-client-dist.zip"
  on:
    branch: master